# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 00:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('upload_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('title', models.TextField(default='title')),
                ('file', models.FileField(default=None, upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('title', models.TextField(default='None', max_length=50)),
                ('short_description', models.TextField(default='', max_length=200)),
                ('detailed_description', models.TextField(default='', max_length=5000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_private', models.BooleanField(default=False)),
                ('encrypted', models.BooleanField(default=False)),
                ('file', models.FileField(default='0b0', upload_to='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
