# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='encrypted',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='reports.Report'),
        ),
    ]
