# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 16:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('is_root', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RootFolder',
            fields=[
                ('folder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.Folder')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='root_folder', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('reports.folder',),
        ),
        migrations.CreateModel(
            name='SubFolder',
            fields=[
                ('folder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.Folder')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_folder', to='reports.Folder')),
            ],
            bases=('reports.folder',),
        ),
    ]
