# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 19:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0002_report_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='favorited_by',
            field=models.ManyToManyField(related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
