# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 15:12
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('upload_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('title', models.TextField(default='title')),
                ('file', models.FileField(default=None, upload_to='')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2016, 11, 7, 10, 12, 32, 535162))),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('title', models.TextField(default='None', max_length=50)),
                ('encrypted', models.BooleanField(default=False)),
                ('file', models.FileField(default='0b0', upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
