# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 19:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 30, 19, 56, 48, 215964)),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='title',
            field=models.TextField(default='title'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
