# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 17:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20161030_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 31, 13, 37, 40, 484328)),
        ),
    ]
