# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 17:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_auto_20161107_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 7, 12, 24, 57, 1315)),
        ),
    ]
